// Top US colleges for affiliate dropdown autofill
export const COMMON_US_COLLEGES = [
  // Ivy League
  { name: 'Harvard University', state: 'MA', city: 'Cambridge' },
  { name: 'Yale University', state: 'CT', city: 'New Haven' },
  { name: 'Princeton University', state: 'NJ', city: 'Princeton' },
  { name: 'Columbia University', state: 'NY', city: 'New York' },
  { name: 'University of Pennsylvania', state: 'PA', city: 'Philadelphia' },
  { name: 'Brown University', state: 'RI', city: 'Providence' },
  { name: 'Dartmouth College', state: 'NH', city: 'Hanover' },
  { name: 'Cornell University', state: 'NY', city: 'Ithaca' },

  // Top Public Universities
  { name: 'University of California, Berkeley', state: 'CA', city: 'Berkeley' },
  { name: 'University of California, Los Angeles', state: 'CA', city: 'Los Angeles' },
  { name: 'University of Michigan', state: 'MI', city: 'Ann Arbor' },
  { name: 'University of Virginia', state: 'VA', city: 'Charlottesville' },
  { name: 'University of North Carolina at Chapel Hill', state: 'NC', city: 'Chapel Hill' },
  { name: 'University of Florida', state: 'FL', city: 'Gainesville' },
  { name: 'University of Texas at Austin', state: 'TX', city: 'Austin' },
  { name: 'University of Washington', state: 'WA', city: 'Seattle' },
  { name: 'University of Wisconsin-Madison', state: 'WI', city: 'Madison' },
  { name: 'University of Illinois Urbana-Champaign', state: 'IL', city: 'Champaign' },
  { name: 'Ohio State University', state: 'OH', city: 'Columbus' },
  { name: 'Pennsylvania State University', state: 'PA', city: 'University Park' },
  { name: 'Purdue University', state: 'IN', city: 'West Lafayette' },

  // UC System
  { name: 'University of California, San Diego', state: 'CA', city: 'San Diego' },
  { name: 'University of California, Davis', state: 'CA', city: 'Davis' },
  { name: 'University of California, Santa Barbara', state: 'CA', city: 'Santa Barbara' },
  { name: 'University of California, Irvine', state: 'CA', city: 'Irvine' },

  // Top Private Universities
  { name: 'Stanford University', state: 'CA', city: 'Stanford' },
  { name: 'Massachusetts Institute of Technology', state: 'MA', city: 'Cambridge' },
  { name: 'Duke University', state: 'NC', city: 'Durham' },
  { name: 'Northwestern University', state: 'IL', city: 'Evanston' },
  { name: 'Vanderbilt University', state: 'TN', city: 'Nashville' },
  { name: 'Rice University', state: 'TX', city: 'Houston' },
  { name: 'University of Notre Dame', state: 'IN', city: 'Notre Dame' },
  { name: 'Emory University', state: 'GA', city: 'Atlanta' },
  { name: 'Carnegie Mellon University', state: 'PA', city: 'Pittsburgh' },
  { name: 'Georgetown University', state: 'DC', city: 'Washington' },
  { name: 'New York University', state: 'NY', city: 'New York' },
  { name: 'University of Southern California', state: 'CA', city: 'Los Angeles' },
  { name: 'Boston University', state: 'MA', city: 'Boston' },
  { name: 'Boston College', state: 'MA', city: 'Chestnut Hill' },

  // Liberal Arts Colleges
  { name: 'Williams College', state: 'MA', city: 'Williamstown' },
  { name: 'Amherst College', state: 'MA', city: 'Amherst' },
  { name: 'Swarthmore College', state: 'PA', city: 'Swarthmore' },
  { name: 'Pomona College', state: 'CA', city: 'Claremont' },
  { name: 'Wellesley College', state: 'MA', city: 'Wellesley' },
  { name: 'Bowdoin College', state: 'ME', city: 'Brunswick' },
  { name: 'Carleton College', state: 'MN', city: 'Northfield' },
  { name: 'Middlebury College', state: 'VT', city: 'Middlebury' },
  { name: 'Claremont McKenna College', state: 'CA', city: 'Claremont' },

  // Large State Universities
  { name: 'University of Georgia', state: 'GA', city: 'Athens' },
  { name: 'University of Maryland', state: 'MD', city: 'College Park' },
  { name: 'University of Arizona', state: 'AZ', city: 'Tucson' },
  { name: 'Arizona State University', state: 'AZ', city: 'Tempe' },
  { name: 'Indiana University Bloomington', state: 'IN', city: 'Bloomington' },
  { name: 'Michigan State University', state: 'MI', city: 'East Lansing' },
  { name: 'Rutgers University', state: 'NJ', city: 'New Brunswick' },
  { name: 'University of Minnesota Twin Cities', state: 'MN', city: 'Minneapolis' },
  { name: 'University of Colorado Boulder', state: 'CO', city: 'Boulder' },
  { name: 'University of Iowa', state: 'IA', city: 'Iowa City' },
  { name: 'University of Pittsburgh', state: 'PA', city: 'Pittsburgh' },
  { name: 'University of Tennessee', state: 'TN', city: 'Knoxville' },
  { name: 'University of Alabama', state: 'AL', city: 'Tuscaloosa' },
  { name: 'University of South Carolina', state: 'SC', city: 'Columbia' },
  { name: 'University of Connecticut', state: 'CT', city: 'Storrs' },
  { name: 'University of Oregon', state: 'OR', city: 'Eugene' },

  // Southern Universities
  { name: 'Florida State University', state: 'FL', city: 'Tallahassee' },
  { name: 'University of Miami', state: 'FL', city: 'Coral Gables' },
  { name: 'Clemson University', state: 'SC', city: 'Clemson' },
  { name: 'University of Kentucky', state: 'KY', city: 'Lexington' },
  { name: 'Louisiana State University', state: 'LA', city: 'Baton Rouge' },
  { name: 'Auburn University', state: 'AL', city: 'Auburn' },
  { name: 'Texas A&M University', state: 'TX', city: 'College Station' },
  { name: 'Tulane University', state: 'LA', city: 'New Orleans' },

  // Midwest Universities
  { name: 'University of Kansas', state: 'KS', city: 'Lawrence' },
  { name: 'University of Missouri', state: 'MO', city: 'Columbia' },
  { name: 'University of Nebraska', state: 'NE', city: 'Lincoln' },
  { name: 'University of Oklahoma', state: 'OK', city: 'Norman' },
  { name: 'Iowa State University', state: 'IA', city: 'Ames' },
  { name: 'Kansas State University', state: 'KS', city: 'Manhattan' },
  { name: 'Washington University in St. Louis', state: 'MO', city: 'St. Louis' },

  // West Coast Universities
  { name: 'University of Washington Seattle', state: 'WA', city: 'Seattle' },
  { name: 'University of Utah', state: 'UT', city: 'Salt Lake City' },
  { name: 'University of Nevada, Reno', state: 'NV', city: 'Reno' },
  { name: 'University of Hawaii at Manoa', state: 'HI', city: 'Honolulu' },
  { name: 'San Diego State University', state: 'CA', city: 'San Diego' },
  { name: 'California Polytechnic State University', state: 'CA', city: 'San Luis Obispo' },
  { name: 'Santa Clara University', state: 'CA', city: 'Santa Clara' },

  // East Coast Universities
  { name: 'Syracuse University', state: 'NY', city: 'Syracuse' },
  { name: 'University at Buffalo', state: 'NY', city: 'Buffalo' },
  { name: 'Northeastern University', state: 'MA', city: 'Boston' },
  { name: 'University of Rochester', state: 'NY', city: 'Rochester' },
  { name: 'Tufts University', state: 'MA', city: 'Medford' },
  { name: 'Brandeis University', state: 'MA', city: 'Waltham' },
  { name: 'University of Delaware', state: 'DE', city: 'Newark' },
  { name: 'Villanova University', state: 'PA', city: 'Villanova' },
  { name: 'Lehigh University', state: 'PA', city: 'Bethlehem' },

  // Additional Notable Universities
  { name: 'Baylor University', state: 'TX', city: 'Waco' },
  { name: 'University of Arkansas', state: 'AR', city: 'Fayetteville' },
  { name: 'West Virginia University', state: 'WV', city: 'Morgantown' },
  { name: 'University of Mississippi', state: 'MS', city: 'Oxford' },
  { name: 'Mississippi State University', state: 'MS', city: 'Mississippi State' },
  { name: 'University of New Mexico', state: 'NM', city: 'Albuquerque' },
  { name: 'George Washington University', state: 'DC', city: 'Washington' },
  { name: 'American University', state: 'DC', city: 'Washington' },
  { name: 'Fordham University', state: 'NY', city: 'Bronx' },
  { name: 'Hofstra University', state: 'NY', city: 'Hempstead' },
  { name: 'Pepperdine University', state: 'CA', city: 'Malibu' },
  { name: 'Loyola Marymount University', state: 'CA', city: 'Los Angeles' },
  { name: 'University of San Diego', state: 'CA', city: 'San Diego' },
  { name: 'Chapman University', state: 'CA', city: 'Orange' },
  { name: 'University of the Pacific', state: 'CA', city: 'Stockton' },
];
